package pojos;
// Generated 6/10/2015 12:22:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Almacen generated by hbm2java
 */
@Entity
@Table(name="almacen"
    ,catalog="adminedredon"
)
public class Almacen  implements java.io.Serializable {


     private int idAlmacen;
     private String nombre;
     private Integer minimo;
     private Integer existencias;

    public Almacen() {
    }

	
    public Almacen(int idAlmacen) {
        this.idAlmacen = idAlmacen;
    }
    public Almacen(int idAlmacen, String nombre, Integer minimo, Integer existencias) {
       this.idAlmacen = idAlmacen;
       this.nombre = nombre;
       this.minimo = minimo;
       this.existencias = existencias;
    }
   
     @Id 

    
    @Column(name="idAlmacen", unique=true, nullable=false)
    public int getIdAlmacen() {
        return this.idAlmacen;
    }
    
    public void setIdAlmacen(int idAlmacen) {
        this.idAlmacen = idAlmacen;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="minimo")
    public Integer getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(Integer minimo) {
        this.minimo = minimo;
    }

    
    @Column(name="existencias")
    public Integer getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(Integer existencias) {
        this.existencias = existencias;
    }




}


