package pojos;
// Generated 6/10/2015 12:22:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="adminedredon"
)
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String rfc;
     private String curp;
     private String calle;
     private Integer noExterior;
     private Integer noInterior;
     private String referencia;
     private String cp;
     private String telFijo;
     private String telMovil;
     private String email;
     private String pais;
     private String estado;
     private String localidad;
     private Boolean limiteCredito;
     private Double creditoAprobado;

    public Clientes() {
    }

	
    public Clientes(int idCliente, String nombre) {
        this.idCliente = idCliente;
        this.nombre = nombre;
    }
    public Clientes(int idCliente, String nombre, String rfc, String curp, String calle, Integer noExterior, Integer noInterior, String referencia, String cp, String telFijo, String telMovil, String email, String pais, String estado, String localidad, Boolean limiteCredito, Double creditoAprobado) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.rfc = rfc;
       this.curp = curp;
       this.calle = calle;
       this.noExterior = noExterior;
       this.noInterior = noInterior;
       this.referencia = referencia;
       this.cp = cp;
       this.telFijo = telFijo;
       this.telMovil = telMovil;
       this.email = email;
       this.pais = pais;
       this.estado = estado;
       this.localidad = localidad;
       this.limiteCredito = limiteCredito;
       this.creditoAprobado = creditoAprobado;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="RFC", length=20)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    
    @Column(name="CURP", length=25)
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }

    
    @Column(name="calle", length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="noExterior")
    public Integer getNoExterior() {
        return this.noExterior;
    }
    
    public void setNoExterior(Integer noExterior) {
        this.noExterior = noExterior;
    }

    
    @Column(name="noInterior")
    public Integer getNoInterior() {
        return this.noInterior;
    }
    
    public void setNoInterior(Integer noInterior) {
        this.noInterior = noInterior;
    }

    
    @Column(name="referencia", length=100)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="cp", length=10)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }

    
    @Column(name="telFijo", length=45)
    public String getTelFijo() {
        return this.telFijo;
    }
    
    public void setTelFijo(String telFijo) {
        this.telFijo = telFijo;
    }

    
    @Column(name="telMovil", length=45)
    public String getTelMovil() {
        return this.telMovil;
    }
    
    public void setTelMovil(String telMovil) {
        this.telMovil = telMovil;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pais", length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="localidad", length=45)
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    
    @Column(name="limiteCredito")
    public Boolean getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(Boolean limiteCredito) {
        this.limiteCredito = limiteCredito;
    }

    
    @Column(name="creditoAprobado", precision=22, scale=0)
    public Double getCreditoAprobado() {
        return this.creditoAprobado;
    }
    
    public void setCreditoAprobado(Double creditoAprobado) {
        this.creditoAprobado = creditoAprobado;
    }




}


