package pojos;
// Generated 3/10/2015 12:34:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="adminedredon"
)
public class Compra  implements java.io.Serializable {


     private int idCompras;
     private Date fechaCompra;
     private Date fechaCompraSaldada;
     private Date fechaUltimoAbono;
     private Integer sucursal;
     private String nombreSucursal;
     private Integer detalleCompra;
     private String observacion;
     private Double abono;
     private Double importe;
     private Boolean estatus;
     private String tipoDeGasto;
     private Integer proveedorCompra;
     private String nombreProveedor;
     private Boolean credito;
     private String tipoGasto;
     private String metodoPago;

    public Compra() {
    }

	
    public Compra(int idCompras) {
        this.idCompras = idCompras;
    }
    public Compra(int idCompras, Date fechaCompra, Date fechaCompraSaldada, Date fechaUltimoAbono, Integer sucursal, String nombreSucursal, Integer detalleCompra, String observacion, Double abono, Double importe, Boolean estatus, String tipoDeGasto, Integer proveedorCompra, String nombreProveedor, Boolean credito, String tipoGasto, String metodoPago) {
       this.idCompras = idCompras;
       this.fechaCompra = fechaCompra;
       this.fechaCompraSaldada = fechaCompraSaldada;
       this.fechaUltimoAbono = fechaUltimoAbono;
       this.sucursal = sucursal;
       this.nombreSucursal = nombreSucursal;
       this.detalleCompra = detalleCompra;
       this.observacion = observacion;
       this.abono = abono;
       this.importe = importe;
       this.estatus = estatus;
       this.tipoDeGasto = tipoDeGasto;
       this.proveedorCompra = proveedorCompra;
       this.nombreProveedor = nombreProveedor;
       this.credito = credito;
       this.tipoGasto = tipoGasto;
       this.metodoPago = metodoPago;
    }
   
     @Id 

    
    @Column(name="idCompras", unique=true, nullable=false)
    public int getIdCompras() {
        return this.idCompras;
    }
    
    public void setIdCompras(int idCompras) {
        this.idCompras = idCompras;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCompra", length=19)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCompraSaldada", length=19)
    public Date getFechaCompraSaldada() {
        return this.fechaCompraSaldada;
    }
    
    public void setFechaCompraSaldada(Date fechaCompraSaldada) {
        this.fechaCompraSaldada = fechaCompraSaldada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaUltimoAbono", length=19)
    public Date getFechaUltimoAbono() {
        return this.fechaUltimoAbono;
    }
    
    public void setFechaUltimoAbono(Date fechaUltimoAbono) {
        this.fechaUltimoAbono = fechaUltimoAbono;
    }

    
    @Column(name="sucursal")
    public Integer getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Integer sucursal) {
        this.sucursal = sucursal;
    }

    
    @Column(name="nombreSucursal", length=45)
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }

    
    @Column(name="detalleCompra")
    public Integer getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(Integer detalleCompra) {
        this.detalleCompra = detalleCompra;
    }

    
    @Column(name="observacion", length=200)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="abono", precision=22, scale=0)
    public Double getAbono() {
        return this.abono;
    }
    
    public void setAbono(Double abono) {
        this.abono = abono;
    }

    
    @Column(name="importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }

    
    @Column(name="estatus")
    public Boolean getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Boolean estatus) {
        this.estatus = estatus;
    }

    
    @Column(name="tipoDeGasto", length=45)
    public String getTipoDeGasto() {
        return this.tipoDeGasto;
    }
    
    public void setTipoDeGasto(String tipoDeGasto) {
        this.tipoDeGasto = tipoDeGasto;
    }

    
    @Column(name="proveedorCompra")
    public Integer getProveedorCompra() {
        return this.proveedorCompra;
    }
    
    public void setProveedorCompra(Integer proveedorCompra) {
        this.proveedorCompra = proveedorCompra;
    }

    
    @Column(name="nombreProveedor", length=45)
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }

    
    @Column(name="credito")
    public Boolean getCredito() {
        return this.credito;
    }
    
    public void setCredito(Boolean credito) {
        this.credito = credito;
    }

    
    @Column(name="tipoGasto", length=45)
    public String getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(String tipoGasto) {
        this.tipoGasto = tipoGasto;
    }

    
    @Column(name="metodoPago", length=45)
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }




}


