package pojos;
// Generated 7/11/2015 02:25:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="adminedredon"
)
public class Compra  implements java.io.Serializable {


     private Integer idCompras;
     private String nota;
     private Date fechaCompra;
     private Date fechaCompraSaldada;
     private Date fechaUltimoAbono;
     private String nombreSucursal;
     private Integer detalleCompra;
     private String observacion;
     private Double abono;
     private Double importe;
     private String estatus;
     private String tipoDeGasto;
     private String nombreProveedor;
     private Boolean credito;
     private String tipoGasto;
     private String metodoPago;
     private String nombreProducto;
     private Integer noPiezas;
     private Double saldoRestante;
     private Double precioUnitario;

    public Compra() {
    }

    public Compra(String nota, Date fechaCompra, Date fechaCompraSaldada, Date fechaUltimoAbono, String nombreSucursal, Integer detalleCompra, String observacion, Double abono, Double importe, String estatus, String tipoDeGasto, String nombreProveedor, Boolean credito, String tipoGasto, String metodoPago, String nombreProducto, Integer noPiezas, Double saldoRestante, Double precioUnitario) {
       this.nota = nota;
       this.fechaCompra = fechaCompra;
       this.fechaCompraSaldada = fechaCompraSaldada;
       this.fechaUltimoAbono = fechaUltimoAbono;
       this.nombreSucursal = nombreSucursal;
       this.detalleCompra = detalleCompra;
       this.observacion = observacion;
       this.abono = abono;
       this.importe = importe;
       this.estatus = estatus;
       this.tipoDeGasto = tipoDeGasto;
       this.nombreProveedor = nombreProveedor;
       this.credito = credito;
       this.tipoGasto = tipoGasto;
       this.metodoPago = metodoPago;
       this.nombreProducto = nombreProducto;
       this.noPiezas = noPiezas;
       this.saldoRestante = saldoRestante;
       this.precioUnitario = precioUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCompras", unique=true, nullable=false)
    public Integer getIdCompras() {
        return this.idCompras;
    }
    
    public void setIdCompras(Integer idCompras) {
        this.idCompras = idCompras;
    }

    
    @Column(name="nota", length=45)
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCompra", length=19)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCompraSaldada", length=19)
    public Date getFechaCompraSaldada() {
        return this.fechaCompraSaldada;
    }
    
    public void setFechaCompraSaldada(Date fechaCompraSaldada) {
        this.fechaCompraSaldada = fechaCompraSaldada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaUltimoAbono", length=19)
    public Date getFechaUltimoAbono() {
        return this.fechaUltimoAbono;
    }
    
    public void setFechaUltimoAbono(Date fechaUltimoAbono) {
        this.fechaUltimoAbono = fechaUltimoAbono;
    }

    
    @Column(name="nombreSucursal", length=45)
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }

    
    @Column(name="detalleCompra")
    public Integer getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(Integer detalleCompra) {
        this.detalleCompra = detalleCompra;
    }

    
    @Column(name="observacion", length=200)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="abono", precision=22, scale=0)
    public Double getAbono() {
        return this.abono;
    }
    
    public void setAbono(Double abono) {
        this.abono = abono;
    }

    
    @Column(name="importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }

    
    @Column(name="estatus", length=15)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    
    @Column(name="tipoDeGasto", length=45)
    public String getTipoDeGasto() {
        return this.tipoDeGasto;
    }
    
    public void setTipoDeGasto(String tipoDeGasto) {
        this.tipoDeGasto = tipoDeGasto;
    }

    
    @Column(name="nombreProveedor", length=45)
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }

    
    @Column(name="credito")
    public Boolean getCredito() {
        return this.credito;
    }
    
    public void setCredito(Boolean credito) {
        this.credito = credito;
    }

    
    @Column(name="tipoGasto", length=45)
    public String getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(String tipoGasto) {
        this.tipoGasto = tipoGasto;
    }

    
    @Column(name="metodoPago", length=45)
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }

    
    @Column(name="nombreProducto", length=45)
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    
    @Column(name="noPiezas")
    public Integer getNoPiezas() {
        return this.noPiezas;
    }
    
    public void setNoPiezas(Integer noPiezas) {
        this.noPiezas = noPiezas;
    }

    
    @Column(name="saldoRestante", precision=22, scale=0)
    public Double getSaldoRestante() {
        return this.saldoRestante;
    }
    
    public void setSaldoRestante(Double saldoRestante) {
        this.saldoRestante = saldoRestante;
    }

    
    @Column(name="precioUnitario", precision=22, scale=0)
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }




}


