package pojos;
// Generated 30/03/2016 06:14:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contenidoexpediente generated by hbm2java
 */
@Entity
@Table(name="contenidoexpediente"
    ,catalog="adminedredon"
)
public class Contenidoexpediente  implements java.io.Serializable {


     private int idContenidoExpediente;
     private Integer idExpediente;
     private Date fecha;
     private String folio;
     private String producto;
     private Integer piezas;
     private Double importe;
     private String formaDePago;
     private String estadoIndividualFolio;

    public Contenidoexpediente() {
    }

	
    public Contenidoexpediente(int idContenidoExpediente) {
        this.idContenidoExpediente = idContenidoExpediente;
    }
    public Contenidoexpediente(int idContenidoExpediente, Integer idExpediente, Date fecha, String folio, String producto, Integer piezas, Double importe, String formaDePago, String estadoIndividualFolio) {
       this.idContenidoExpediente = idContenidoExpediente;
       this.idExpediente = idExpediente;
       this.fecha = fecha;
       this.folio = folio;
       this.producto = producto;
       this.piezas = piezas;
       this.importe = importe;
       this.formaDePago = formaDePago;
       this.estadoIndividualFolio = estadoIndividualFolio;
    }
   
     @Id 

    
    @Column(name="idContenidoExpediente", unique=true, nullable=false)
    public int getIdContenidoExpediente() {
        return this.idContenidoExpediente;
    }
    
    public void setIdContenidoExpediente(int idContenidoExpediente) {
        this.idContenidoExpediente = idContenidoExpediente;
    }

    
    @Column(name="idExpediente")
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="folio", length=45)
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }

    
    @Column(name="producto", length=45)
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }

    
    @Column(name="piezas")
    public Integer getPiezas() {
        return this.piezas;
    }
    
    public void setPiezas(Integer piezas) {
        this.piezas = piezas;
    }

    
    @Column(name="importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }

    
    @Column(name="formaDePago", length=45)
    public String getFormaDePago() {
        return this.formaDePago;
    }
    
    public void setFormaDePago(String formaDePago) {
        this.formaDePago = formaDePago;
    }

    
    @Column(name="estadoIndividualFolio", length=45)
    public String getEstadoIndividualFolio() {
        return this.estadoIndividualFolio;
    }
    
    public void setEstadoIndividualFolio(String estadoIndividualFolio) {
        this.estadoIndividualFolio = estadoIndividualFolio;
    }




}


