package pojos;
// Generated 6/10/2015 12:22:35 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Detalleventa generated by hbm2java
 */
@Entity
@Table(name="detalleventa"
    ,catalog="adminedredon"
)
public class Detalleventa  implements java.io.Serializable {


     private DetalleventaId id;
     private Integer producto;
     private Integer tienda;
     private String descripcion;
     private Integer productoIdProducto;
     private String detalleCompracol;

    public Detalleventa() {
    }

	
    public Detalleventa(DetalleventaId id) {
        this.id = id;
    }
    public Detalleventa(DetalleventaId id, Integer producto, Integer tienda, String descripcion, Integer productoIdProducto, String detalleCompracol) {
       this.id = id;
       this.producto = producto;
       this.tienda = tienda;
       this.descripcion = descripcion;
       this.productoIdProducto = productoIdProducto;
       this.detalleCompracol = detalleCompracol;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iddetalleCompra", column=@Column(name="iddetalleCompra", nullable=false) ), 
        @AttributeOverride(name="comprasIdCompras", column=@Column(name="Compras_idCompras", nullable=false) ) } )
    public DetalleventaId getId() {
        return this.id;
    }
    
    public void setId(DetalleventaId id) {
        this.id = id;
    }

    
    @Column(name="producto")
    public Integer getProducto() {
        return this.producto;
    }
    
    public void setProducto(Integer producto) {
        this.producto = producto;
    }

    
    @Column(name="tienda")
    public Integer getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Integer tienda) {
        this.tienda = tienda;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="Producto_idProducto")
    public Integer getProductoIdProducto() {
        return this.productoIdProducto;
    }
    
    public void setProductoIdProducto(Integer productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }

    
    @Column(name="detalleCompracol", length=45)
    public String getDetalleCompracol() {
        return this.detalleCompracol;
    }
    
    public void setDetalleCompracol(String detalleCompracol) {
        this.detalleCompracol = detalleCompracol;
    }




}


