package pojos;
// Generated 30/03/2016 06:14:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name="expediente"
    ,catalog="adminedredon"
)
public class Expediente  implements java.io.Serializable {


     private int idExpediente;
     private Integer idProveedor;
     private String nombreProveedor;
     private Date fechaApertura;
     private String folio;
     private Double importeGeneral;
     private String estadoGeneral;

    public Expediente() {
    }

	
    public Expediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }
    public Expediente(int idExpediente, Integer idProveedor, String nombreProveedor, Date fechaApertura, String folio, Double importeGeneral, String estadoGeneral) {
       this.idExpediente = idExpediente;
       this.idProveedor = idProveedor;
       this.nombreProveedor = nombreProveedor;
       this.fechaApertura = fechaApertura;
       this.folio = folio;
       this.importeGeneral = importeGeneral;
       this.estadoGeneral = estadoGeneral;
    }
   
     @Id 

    
    @Column(name="idExpediente", unique=true, nullable=false)
    public int getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }

    
    @Column(name="idProveedor")
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombreProveedor", length=45)
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaApertura", length=10)
    public Date getFechaApertura() {
        return this.fechaApertura;
    }
    
    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    
    @Column(name="folio", length=45)
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }

    
    @Column(name="importeGeneral", precision=22, scale=0)
    public Double getImporteGeneral() {
        return this.importeGeneral;
    }
    
    public void setImporteGeneral(Double importeGeneral) {
        this.importeGeneral = importeGeneral;
    }

    
    @Column(name="estadoGeneral", length=45)
    public String getEstadoGeneral() {
        return this.estadoGeneral;
    }
    
    public void setEstadoGeneral(String estadoGeneral) {
        this.estadoGeneral = estadoGeneral;
    }




}


