package pojos;
// Generated 1/05/2016 12:22:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name="expediente"
    ,catalog="adminedredon"
)
public class Expediente  implements java.io.Serializable {


     private Integer idExpediente;
     private Integer idProveedor;
     private String nombreProveedor;
     private Date fechaApertura;
     private String estadoGeneral;

    public Expediente() {
    }

    public Expediente(Integer idProveedor, String nombreProveedor, Date fechaApertura, String estadoGeneral) {
       this.idProveedor = idProveedor;
       this.nombreProveedor = nombreProveedor;
       this.fechaApertura = fechaApertura;
       this.estadoGeneral = estadoGeneral;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idExpediente", unique=true, nullable=false)
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }

    
    @Column(name="idProveedor")
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombreProveedor", length=45)
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaApertura", length=10)
    public Date getFechaApertura() {
        return this.fechaApertura;
    }
    
    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    
    @Column(name="estadoGeneral", length=45)
    public String getEstadoGeneral() {
        return this.estadoGeneral;
    }
    
    public void setEstadoGeneral(String estadoGeneral) {
        this.estadoGeneral = estadoGeneral;
    }




}


