package pojos;
// Generated 1/05/2016 12:22:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gastosfinancieros generated by hbm2java
 */
@Entity
@Table(name="gastosfinancieros"
    ,catalog="adminedredon"
)
public class Gastosfinancieros  implements java.io.Serializable {


     private Integer idGastosFinancieros;
     private Date fecha;
     private String concepto;
     private Double importe;
     private String comentarios;
     private String acreedor;

    public Gastosfinancieros() {
    }

    public Gastosfinancieros(Date fecha, String concepto, Double importe, String comentarios, String acreedor) {
       this.fecha = fecha;
       this.concepto = concepto;
       this.importe = importe;
       this.comentarios = comentarios;
       this.acreedor = acreedor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idGastosFinancieros", unique=true, nullable=false)
    public Integer getIdGastosFinancieros() {
        return this.idGastosFinancieros;
    }
    
    public void setIdGastosFinancieros(Integer idGastosFinancieros) {
        this.idGastosFinancieros = idGastosFinancieros;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="concepto", length=65)
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    
    @Column(name="importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }

    
    @Column(name="comentarios", length=70)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    
    @Column(name="acreedor", length=70)
    public String getAcreedor() {
        return this.acreedor;
    }
    
    public void setAcreedor(String acreedor) {
        this.acreedor = acreedor;
    }




}


