package pojos;
// Generated 14/04/2016 03:19:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gastospersonales generated by hbm2java
 */
@Entity
@Table(name="gastospersonales"
    ,catalog="adminedredon"
)
public class Gastospersonales  implements java.io.Serializable {


     private Integer idGastosPersonales;
     private Date fecha;
     private String concepto;
     private String comentarios;
     private Double importe;

    public Gastospersonales() {
    }

    public Gastospersonales(Date fecha, String concepto, String comentarios, Double importe) {
       this.fecha = fecha;
       this.concepto = concepto;
       this.comentarios = comentarios;
       this.importe = importe;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idGastosPersonales", unique=true, nullable=false)
    public Integer getIdGastosPersonales() {
        return this.idGastosPersonales;
    }
    
    public void setIdGastosPersonales(Integer idGastosPersonales) {
        this.idGastosPersonales = idGastosPersonales;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="concepto", length=45)
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    
    @Column(name="comentarios", length=45)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    
    @Column(name="importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }




}


