package pojos;
// Generated 1/05/2016 12:22:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gastomantenimientov generated by hbm2java
 */
@Entity
@Table(name="gastomantenimientov"
    ,catalog="adminedredon"
)
public class Gastomantenimientov  implements java.io.Serializable {


     private Integer idGastoMantenimientoV;
     private Date fecha;
     private String vehiculo;
     private String mantenimiento;
     private String comentario;
     private Double importe;

    public Gastomantenimientov() {
    }

    public Gastomantenimientov(Date fecha, String vehiculo, String mantenimiento, String comentario, Double importe) {
       this.fecha = fecha;
       this.vehiculo = vehiculo;
       this.mantenimiento = mantenimiento;
       this.comentario = comentario;
       this.importe = importe;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idGastoMantenimientoV", unique=true, nullable=false)
    public Integer getIdGastoMantenimientoV() {
        return this.idGastoMantenimientoV;
    }
    
    public void setIdGastoMantenimientoV(Integer idGastoMantenimientoV) {
        this.idGastoMantenimientoV = idGastoMantenimientoV;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="vehiculo", length=45)
    public String getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(String vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="mantenimiento", length=45)
    public String getMantenimiento() {
        return this.mantenimiento;
    }
    
    public void setMantenimiento(String mantenimiento) {
        this.mantenimiento = mantenimiento;
    }

    
    @Column(name="comentario", length=45)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }




}


