package pojos;
// Generated 6/10/2015 12:22:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name="proveedores"
    ,catalog="adminedredon"
)
public class Proveedores  implements java.io.Serializable {


     private int idProveedor;
     private String nombre;
     private String rfc;
     private String calle;
     private Integer noExterior;
     private Integer noInterior;
     private String referencia;
     private String cp;
     private String telFijo;
     private String telMovil;
     private String email;
     private String pais;
     private String estado;
     private String localidad;

    public Proveedores() {
    }

	
    public Proveedores(int idProveedor, String nombre) {
        this.idProveedor = idProveedor;
        this.nombre = nombre;
    }
    public Proveedores(int idProveedor, String nombre, String rfc, String calle, Integer noExterior, Integer noInterior, String referencia, String cp, String telFijo, String telMovil, String email, String pais, String estado, String localidad) {
       this.idProveedor = idProveedor;
       this.nombre = nombre;
       this.rfc = rfc;
       this.calle = calle;
       this.noExterior = noExterior;
       this.noInterior = noInterior;
       this.referencia = referencia;
       this.cp = cp;
       this.telFijo = telFijo;
       this.telMovil = telMovil;
       this.email = email;
       this.pais = pais;
       this.estado = estado;
       this.localidad = localidad;
    }
   
     @Id 

    
    @Column(name="idProveedor", unique=true, nullable=false)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="RFC", length=20)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    
    @Column(name="calle", length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="noExterior")
    public Integer getNoExterior() {
        return this.noExterior;
    }
    
    public void setNoExterior(Integer noExterior) {
        this.noExterior = noExterior;
    }

    
    @Column(name="noInterior")
    public Integer getNoInterior() {
        return this.noInterior;
    }
    
    public void setNoInterior(Integer noInterior) {
        this.noInterior = noInterior;
    }

    
    @Column(name="referencia", length=100)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="cp", length=10)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }

    
    @Column(name="telFijo", length=45)
    public String getTelFijo() {
        return this.telFijo;
    }
    
    public void setTelFijo(String telFijo) {
        this.telFijo = telFijo;
    }

    
    @Column(name="telMovil", length=45)
    public String getTelMovil() {
        return this.telMovil;
    }
    
    public void setTelMovil(String telMovil) {
        this.telMovil = telMovil;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pais", length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="localidad", length=45)
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


