package pojos;
// Generated 7/11/2015 02:25:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sublinea generated by hbm2java
 */
@Entity
@Table(name="sublinea"
    ,catalog="adminedredon"
)
public class Sublinea  implements java.io.Serializable {


     private Integer idSublinea;
     private String nombre;

    public Sublinea() {
    }

    public Sublinea(String nombre) {
       this.nombre = nombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSublinea", unique=true, nullable=false)
    public Integer getIdSublinea() {
        return this.idSublinea;
    }
    
    public void setIdSublinea(Integer idSublinea) {
        this.idSublinea = idSublinea;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


