package pojos;
// Generated 7/11/2015 02:25:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
    ,catalog="adminedredon"
)
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private String nota;
     private Date fechaVenta;
     private Date fechaVentaSaldada;
     private Date fechaUltimoAbono;
     private Integer detalleVenta;
     private String descripcion;
     private Double abono;
     private String estatus;
     private Integer usuarioUltimoAjuste;
     private Boolean credito;
     private String metodoPago;
     private String nombreCliente;
     private Double saldoRestante;
     private Double importe;
     private String nombreTienda;

    public Venta() {
    }

	
    public Venta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Venta(String nota, Date fechaVenta, Date fechaVentaSaldada, Date fechaUltimoAbono, Integer detalleVenta, String descripcion, Double abono, String estatus, Integer usuarioUltimoAjuste, Boolean credito, String metodoPago, String nombreCliente, Double saldoRestante, Double importe, String nombreTienda) {
       this.nota = nota;
       this.fechaVenta = fechaVenta;
       this.fechaVentaSaldada = fechaVentaSaldada;
       this.fechaUltimoAbono = fechaUltimoAbono;
       this.detalleVenta = detalleVenta;
       this.descripcion = descripcion;
       this.abono = abono;
       this.estatus = estatus;
       this.usuarioUltimoAjuste = usuarioUltimoAjuste;
       this.credito = credito;
       this.metodoPago = metodoPago;
       this.nombreCliente = nombreCliente;
       this.saldoRestante = saldoRestante;
       this.importe = importe;
       this.nombreTienda = nombreTienda;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVenta", unique=true, nullable=false)
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }

    
    @Column(name="nota", length=45)
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaVenta", nullable=false, length=19)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaVentaSaldada", length=19)
    public Date getFechaVentaSaldada() {
        return this.fechaVentaSaldada;
    }
    
    public void setFechaVentaSaldada(Date fechaVentaSaldada) {
        this.fechaVentaSaldada = fechaVentaSaldada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaUltimoAbono", length=19)
    public Date getFechaUltimoAbono() {
        return this.fechaUltimoAbono;
    }
    
    public void setFechaUltimoAbono(Date fechaUltimoAbono) {
        this.fechaUltimoAbono = fechaUltimoAbono;
    }

    
    @Column(name="detalleVenta")
    public Integer getDetalleVenta() {
        return this.detalleVenta;
    }
    
    public void setDetalleVenta(Integer detalleVenta) {
        this.detalleVenta = detalleVenta;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="abono", precision=22, scale=0)
    public Double getAbono() {
        return this.abono;
    }
    
    public void setAbono(Double abono) {
        this.abono = abono;
    }

    
    @Column(name="estatus", length=45)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    
    @Column(name="usuarioUltimoAjuste")
    public Integer getUsuarioUltimoAjuste() {
        return this.usuarioUltimoAjuste;
    }
    
    public void setUsuarioUltimoAjuste(Integer usuarioUltimoAjuste) {
        this.usuarioUltimoAjuste = usuarioUltimoAjuste;
    }

    
    @Column(name="credito")
    public Boolean getCredito() {
        return this.credito;
    }
    
    public void setCredito(Boolean credito) {
        this.credito = credito;
    }

    
    @Column(name="metodoPago", length=45)
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }

    
    @Column(name="nombreCliente", length=100)
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    
    @Column(name="saldoRestante", precision=22, scale=0)
    public Double getSaldoRestante() {
        return this.saldoRestante;
    }
    
    public void setSaldoRestante(Double saldoRestante) {
        this.saldoRestante = saldoRestante;
    }

    
    @Column(name="Importe", precision=22, scale=0)
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }

    
    @Column(name="nombreTienda", length=45)
    public String getNombreTienda() {
        return this.nombreTienda;
    }
    
    public void setNombreTienda(String nombreTienda) {
        this.nombreTienda = nombreTienda;
    }




}


