/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controlBD.DAOUniversalHibernate;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import pojos.Proveedores;

/**
 *
 * @author Daniel
 */
public class CatalogoProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form CatalogoCreditos
     */
    public CatalogoProveedores() {
        initComponents();
        String Query = "";
        Query = "FROM Proveedores p ORDER BY p.nombre";
        cargaTabla(jtProveedor, Query, "Proveedor", 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProveedoresClientes = new javax.swing.JPanel();
        jsProvedorCliente = new javax.swing.JScrollPane();
        jtProveedor = new javax.swing.JTable();
        txtProveedorNuevo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Catalogo de Proveedores");

        jpProveedoresClientes.setBackground(new java.awt.Color(255, 255, 255));
        jpProveedoresClientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpProveedoresClientesComponentShown(evt);
            }
        });

        jtProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Local"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProveedor.setOpaque(false);
        jtProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtProveedorKeyPressed(evt);
            }
        });
        jsProvedorCliente.setViewportView(jtProveedor);

        txtProveedorNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProveedorNuevoKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/proveedor.png"))); // NOI18N

        jLabel113.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(102, 102, 102));
        jLabel113.setText("TEXTO + ENTER = NUEVO");

        jLabel114.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(102, 102, 102));
        jLabel114.setText("TABLA + ENTER = CAMBIAR");

        jLabel115.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(102, 102, 102));
        jLabel115.setText("TABLA + SUPR   = BORRAR");

        jLabel116.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(102, 102, 102));
        jLabel116.setText("<---------------------");

        jLabel117.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(102, 102, 102));
        jLabel117.setText("<---------------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel114, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel116, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel117, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel113)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel117)
                .addGap(51, 51, 51)
                .addComponent(jLabel114)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel115)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel116)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabel112.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(102, 102, 102));
        jLabel112.setText("Proveedores");

        javax.swing.GroupLayout jpProveedoresClientesLayout = new javax.swing.GroupLayout(jpProveedoresClientes);
        jpProveedoresClientes.setLayout(jpProveedoresClientesLayout);
        jpProveedoresClientesLayout.setHorizontalGroup(
            jpProveedoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProveedoresClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProveedoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProveedoresClientesLayout.createSequentialGroup()
                        .addGroup(jpProveedoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProveedorNuevo)
                            .addComponent(jsProvedorCliente))
                        .addGap(8, 8, 8))
                    .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpProveedoresClientesLayout.setVerticalGroup(
            jpProveedoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProveedoresClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProveedoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProveedoresClientesLayout.createSequentialGroup()
                        .addComponent(jLabel112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProveedorNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsProvedorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpProveedoresClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpProveedoresClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void llenarTabla(JTable jtTabla, String nombreTabla, String consulta) {
        DAOUniversalHibernate acceso = new DAOUniversalHibernate();
        jtTabla.setVisible(false);
        jtTabla.removeAll();
        //_________________________ NOMBRE DE LA TABLA, CONSULTA
        jtTabla.setModel(acceso.retornaModelo(nombreTabla, consulta));
        jtTabla.setVisible(true);
    }

    private void cargaTabla(final JTable jtTabla, String HQL, String Encabezado, int NoColOcultar) {
        //Reviso si que la consulta no vaya vacia
        if (!HQL.isEmpty()) {
            DAOUniversalHibernate acceso = new DAOUniversalHibernate();
            jtTabla.setVisible(false);
            jtTabla.removeAll();
            jtTabla.setModel(acceso.retornaModelo(Encabezado, HQL));
            TableColumn column = null;
            for (int i = 0; i < NoColOcultar; i++) {
                column = jtTabla.getColumnModel().getColumn(i);
                column.setMaxWidth(10);
            }
            jtTabla.setVisible(true);
        }
    }

    private void limpiarCampos() {

        txtProveedorNuevo.setText("");

    }
    private void jpProveedoresClientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpProveedoresClientesComponentShown
        String Query = "";
        Query = "FROM Proveedores p ORDER BY p.nombre";
        cargaTabla(jtProveedor, Query, "Proveedor", 1);
    }//GEN-LAST:event_jpProveedoresClientesComponentShown

    private void txtProveedorNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorNuevoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DAOUniversalHibernate control = new DAOUniversalHibernate();
            try {
                if (!txtProveedorNuevo.getText().isEmpty()) {
                    pojos.Proveedores proveedor = new pojos.Proveedores();
                    proveedor.setNombre(txtProveedorNuevo.getText());
                    control.add(proveedor);

                    limpiarCampos();
                   
                    String Query = "";
                    Query = "FROM Proveedores p ORDER BY p.nombre";
                    cargaTabla(jtProveedor, Query, "Proveedor", 1);
                } else {
                    JOptionPane.showMessageDialog(this, "Favor de llenar el campo Nombre", "Datos incompletos", 1);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Error", 0);
            }
        }
    }//GEN-LAST:event_txtProveedorNuevoKeyPressed

    private void jtProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtProveedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtProveedor.getSelectedRow() != -1) {
                int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea editar este proveedor?", "Confirmar editar", 0, 3);
                if (respuesta == 0) {
                    try {
                        DAOUniversalHibernate acceso = new DAOUniversalHibernate();
                        int clave = (int) jtProveedor.getValueAt(jtProveedor.getSelectedRow(), 0);
                        String query = "From Proveedores s WHERE s.idProveedor = '" + clave + "'";
                        Proveedores proveedor = (Proveedores) acceso.select(query).get(0);
                        String nombre = JOptionPane.showInputDialog(this, "Nuevo nombre");
                        proveedor.setNombre(nombre);
                        acceso.Update(proveedor);
                        query = "From Proveedores s ORDER BY s.idProveedor";
                        llenarTabla(jtProveedor, "Proveedor", query);
                        JOptionPane.showMessageDialog(this, "Proveedor editada correctamente", "Cancelado", 1);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + e, "Error", 0);
                        System.gc();
                    }
                }
            }
        }
//----------------------------------------------------------------------->
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (jtProveedor.getSelectedRow() != -1) {
                int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea eliminar este proveedor?", "Confirmar eliminación", 0, 3);
                if (respuesta == 0) {
                    try {
                        DAOUniversalHibernate acceso = new DAOUniversalHibernate();
                        int clave = (int) jtProveedor.getValueAt(jtProveedor.getSelectedRow(), 0);
                        String query = "From Proveedores s WHERE s.idProveedor = '" + clave + "'";
                        Proveedores proveedor = (Proveedores) acceso.select(query).get(0);
                        acceso.delete(proveedor);
                        query = "From Proveedores s";
                        llenarTabla(jtProveedor, "Proveedor", query);
                        JOptionPane.showMessageDialog(this, "Proveedor eliminada correctamente", "Cancelado", 1);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + e, "Error", 0);
                        System.gc();
                    }
                }
            }
        }
    }//GEN-LAST:event_jtProveedorKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpProveedoresClientes;
    private javax.swing.JScrollPane jsProvedorCliente;
    private javax.swing.JTable jtProveedor;
    private javax.swing.JTextField txtProveedorNuevo;
    // End of variables declaration//GEN-END:variables
}
