/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controlBD.AccesoBD;
import herramienta.FechaHerramienta;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pojos.Clientes;
import pojos.Venta;

/**
 *
 * @author Daniel
 */
public class DiarioDeCaja extends javax.swing.JInternalFrame {

    String clienteAbono = "";

    public DiarioDeCaja() {
        initComponents();
        jdcFechaCredito.setDate(new Date());
        jdcFechaAbono.setDate(new Date());
        jdcFechaInicio.setDate(new Date());
        jdcFechaFin.setDate(new Date());
        jdcFechaGasto.setDate(new Date());
        addActions();
    }

    private void llenarCombos() {
        //Controles para llenar los comoboBox
        AccesoBD accesoBD = new AccesoBD();
        List listaObjetos = accesoBD.select("From Clientes");
        cmbClienteCredito.removeAllItems();
        cmbClienteAbono.removeAllItems();
        if (listaObjetos.size() > 0) {
            cmbClienteCredito.setEnabled(true);
            cmbClienteAbono.setEnabled(true);
            try {
                //Crea la lista de categorias
                for (int i = 0; i < listaObjetos.size(); i++) {
                    Clientes cliente = (Clientes) listaObjetos.get(i);
                    cmbClienteCredito.addItem(cliente.getIdCliente() + "-" + cliente.getNombre());
                    cmbClienteAbono.addItem(cliente.getIdCliente() + "-" + cliente.getNombre());
                }
                cmbClienteAbono.setSelectedIndex(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "El error es:" + "\n" + e, "Error", 0);
            }

        } else {
            cmbClienteCredito.setEnabled(false);
            cmbClienteAbono.setEnabled(false);
        }

    }

    public boolean exist(JInternalFrame frame) throws Exception {

        try {
            JInternalFrame iframes[] = CPanel.desktop.getAllFrames();
            for (int i = 0; i < iframes.length; i++) {
                if (iframes[i].getTitle().equals(frame.getTitle())) {
                    iframes[i].moveToFront();
                    iframes[i].setSelected(true);
                    iframes[i].setLocation((CPanel.desktop.getWidth() - iframes[i].getWidth()) / 2,
                            (CPanel.desktop.getHeight() - iframes[i].getHeight()) / 2);
                    return true;
                }
            }
        } catch (Exception e) {
            throw e;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpDiario = new javax.swing.JTabbedPane();
        jpCreditos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdcFechaCredito = new com.toedter.calendar.JDateChooser();
        txtNota = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTablaCreditos = new javax.swing.JTable();
        btnAnotar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        btnRegistrarVentas = new javax.swing.JButton();
        btnBorrarCredito = new javax.swing.JButton();
        cmbClienteCredito = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbSucursal = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbMetodoDePago = new javax.swing.JComboBox();
        btnSalir = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtAbonoInicial = new javax.swing.JTextField();
        jpAbonos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTablaAbonos = new javax.swing.JTable();
        btnAbonar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jdcFechaAbono = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        txtCantidadAbono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbClienteAbono = new javax.swing.JComboBox();
        btnSalirAbonos = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        chkTodosLosClientes = new javax.swing.JCheckBox();
        jpGastos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jdcFechaGasto = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtTablaGastos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnAnotar1 = new javax.swing.JButton();
        btnGuardarCreditos1 = new javax.swing.JButton();
        txtConcepto = new javax.swing.JTextField();
        btnSalirGastos = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jpResumen = new javax.swing.JPanel();
        btnSalirResumen = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Diario de Caja");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(240, 79, 90));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Diario de Caja por Tienda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpDiario.setForeground(new java.awt.Color(255, 102, 0));
        jtpDiario.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        jpCreditos.setBackground(new java.awt.Color(255, 255, 255));
        jpCreditos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpCreditosComponentShown(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Cliente");

        btnRegistrarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(0, 153, 51));
        btnRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/mas.png"))); // NOI18N
        btnRegistrarCliente.setText("Nuevo");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Nota");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Fecha de Compra");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Importe");

        jtTablaCreditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nota", "Fecha", "Tienda", "Cliente", "Observación", "Forma de Pago", "Abono Ini.", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtTablaCreditos);
        if (jtTablaCreditos.getColumnModel().getColumnCount() > 0) {
            jtTablaCreditos.getColumnModel().getColumn(0).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtTablaCreditos.getColumnModel().getColumn(1).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(1).setPreferredWidth(50);
            jtTablaCreditos.getColumnModel().getColumn(2).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(3).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(4).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(5).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(5).setPreferredWidth(100);
            jtTablaCreditos.getColumnModel().getColumn(6).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(7).setResizable(false);
            jtTablaCreditos.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        btnAnotar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnotar.setForeground(new java.awt.Color(0, 153, 51));
        btnAnotar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/list.png"))); // NOI18N
        btnAnotar.setText("Anotar");
        btnAnotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnotarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("Observación");

        btnRegistrarVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarVentas.setForeground(new java.awt.Color(0, 153, 51));
        btnRegistrarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/mas.png"))); // NOI18N
        btnRegistrarVentas.setText("Registrar");
        btnRegistrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentasActionPerformed(evt);
            }
        });

        btnBorrarCredito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBorrarCredito.setForeground(new java.awt.Color(0, 153, 51));
        btnBorrarCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/menos.png"))); // NOI18N
        btnBorrarCredito.setText("Quitar");
        btnBorrarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCreditoActionPerformed(evt);
            }
        });

        cmbClienteCredito.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbClienteCredito.setForeground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Tienda donde se hizo el cargo");

        cmbSucursal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbSucursal.setForeground(new java.awt.Color(0, 102, 153));
        cmbSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuaracurio 2", "General", "La Comadre", "La Flor", "La Flor Texti", "Local 2", "Local B5", "Local D7", "Local E15", "Moroleón", " " }));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Quitar una venta");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("Todas la ventas listadas");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Pagó con");

        cmbMetodoDePago.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbMetodoDePago.setForeground(new java.awt.Color(0, 102, 153));
        cmbMetodoDePago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EFECTIVO", "TRANSFERENCIA BANCARIA", "DEVOLUCION", "NOTA DE CREDITO", "CHEQUE", " ", " " }));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/exit2.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("Salir");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 153));
        jLabel28.setText("Abono Inic.");

        javax.swing.GroupLayout jpCreditosLayout = new javax.swing.GroupLayout(jpCreditos);
        jpCreditos.setLayout(jpCreditosLayout);
        jpCreditosLayout.setHorizontalGroup(
            jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCreditosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreditosLayout.createSequentialGroup()
                        .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbSucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(jpCreditosLayout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarCredito)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCreditosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAbonoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrarCliente)
                                    .addComponent(btnAnotar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpCreditosLayout.createSequentialGroup()
                                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpCreditosLayout.createSequentialGroup()
                                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jdcFechaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbMetodoDePago, 0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreditosLayout.createSequentialGroup()
                                        .addComponent(cmbClienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)))))
                        .addGap(124, 124, 124))))
        );

        jpCreditosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnotar, btnRegistrarCliente});

        jpCreditosLayout.setVerticalGroup(
            jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreditosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(btnRegistrarCliente)
                    .addComponent(cmbClienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jdcFechaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbMetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnotar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel28)
                    .addComponent(txtAbonoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel22)
                    .addComponent(btnBorrarCredito)
                    .addComponent(btnRegistrarVentas)
                    .addComponent(jLabel23)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        jtpDiario.addTab("Créditos", jpCreditos);

        jpAbonos.setBackground(new java.awt.Color(255, 255, 255));
        jpAbonos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpAbonosComponentShown(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Inicio");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Fin");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Cliente");

        jtTablaAbonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nota", "Fecha Credito", "Cliente", "Tienda", "Importe", "Fecha Abono", "Abono", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtTablaAbonos);
        if (jtTablaAbonos.getColumnModel().getColumnCount() > 0) {
            jtTablaAbonos.getColumnModel().getColumn(0).setResizable(false);
            jtTablaAbonos.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtTablaAbonos.getColumnModel().getColumn(1).setResizable(false);
            jtTablaAbonos.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtTablaAbonos.getColumnModel().getColumn(2).setResizable(false);
            jtTablaAbonos.getColumnModel().getColumn(3).setResizable(false);
            jtTablaAbonos.getColumnModel().getColumn(4).setResizable(false);
            jtTablaAbonos.getColumnModel().getColumn(5).setResizable(false);
            jtTablaAbonos.getColumnModel().getColumn(7).setResizable(false);
        }

        btnAbonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/dollar.png"))); // NOI18N
        btnAbonar.setText("Abonar");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 153));
        jLabel19.setText("Fecha del abono");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Cantidad");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Lista de créditos");

        cmbClienteAbono.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbClienteAbono.setForeground(new java.awt.Color(0, 102, 153));
        cmbClienteAbono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClienteAbonoItemStateChanged(evt);
            }
        });
        cmbClienteAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteAbonoActionPerformed(evt);
            }
        });

        btnSalirAbonos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalirAbonos.setForeground(new java.awt.Color(0, 153, 51));
        btnSalirAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/exit2.png"))); // NOI18N
        btnSalirAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAbonosActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 153));
        jLabel25.setText("Salir");

        chkTodosLosClientes.setBackground(new java.awt.Color(255, 255, 255));
        chkTodosLosClientes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkTodosLosClientes.setForeground(new java.awt.Color(0, 102, 153));
        chkTodosLosClientes.setText("Mostrar todos");
        chkTodosLosClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkTodosLosClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpAbonosLayout = new javax.swing.GroupLayout(jpAbonos);
        jpAbonos.setLayout(jpAbonosLayout);
        jpAbonosLayout.setHorizontalGroup(
            jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAbonosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAbonosLayout.createSequentialGroup()
                        .addComponent(btnSalirAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAbonosLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbClienteAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(chkTodosLosClientes)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAbonosLayout.createSequentialGroup()
                        .addGroup(jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpAbonosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel19, jdcFechaAbono});

        jpAbonosLayout.setVerticalGroup(
            jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAbonosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jdcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbClienteAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTodosLosClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(jdcFechaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtCantidadAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnSalirAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25)))
                .addContainerGap())
        );

        jtpDiario.addTab("Abonos", jpAbonos);

        jpGastos.setBackground(new java.awt.Color(255, 255, 255));
        jpGastos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpGastosComponentShown(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Concepto");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Importe");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jtTablaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Concepto", "Observaciones", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtTablaGastos);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Observaciones");

        btnAnotar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnotar1.setForeground(new java.awt.Color(0, 153, 51));
        btnAnotar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/apply.png"))); // NOI18N
        btnAnotar1.setText("Anotar");
        btnAnotar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnotar1ActionPerformed(evt);
            }
        });

        btnGuardarCreditos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardarCreditos1.setForeground(new java.awt.Color(0, 153, 51));
        btnGuardarCreditos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/mas.png"))); // NOI18N
        btnGuardarCreditos1.setText("Guardar Gasto");
        btnGuardarCreditos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCreditos1ActionPerformed(evt);
            }
        });

        btnSalirGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalirGastos.setForeground(new java.awt.Color(0, 153, 51));
        btnSalirGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/exit2.png"))); // NOI18N
        btnSalirGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirGastosActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 153));
        jLabel26.setText("Salir");

        javax.swing.GroupLayout jpGastosLayout = new javax.swing.GroupLayout(jpGastos);
        jpGastos.setLayout(jpGastosLayout);
        jpGastosLayout.setHorizontalGroup(
            jpGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jpGastosLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcFechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGastosLayout.createSequentialGroup()
                        .addComponent(btnSalirGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarCreditos1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGastosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnotar1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpGastosLayout.setVerticalGroup(
            jpGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGastosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel21)
                    .addComponent(jdcFechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnotar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarCreditos1)
                    .addComponent(btnSalirGastos, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap())
        );

        jtpDiario.addTab("Gastos", jpGastos);

        jpResumen.setBackground(new java.awt.Color(255, 255, 255));

        btnSalirResumen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalirResumen.setForeground(new java.awt.Color(0, 153, 51));
        btnSalirResumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosGenerales/exit2.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 153));
        jLabel27.setText("Salir");

        javax.swing.GroupLayout jpResumenLayout = new javax.swing.GroupLayout(jpResumen);
        jpResumen.setLayout(jpResumenLayout);
        jpResumenLayout.setHorizontalGroup(
            jpResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalirResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jpResumenLayout.setVerticalGroup(
            jpResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpResumenLayout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(jpResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(btnSalirResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtpDiario.addTab("Resumen", jpResumen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 801, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpDiario))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed

        try {
            RegistroCliente registroCliente = new RegistroCliente();
            if (exist(registroCliente) == false) {
                CPanel.desktop.add(registroCliente);
                registroCliente.setVisible(true);
                registroCliente.setLocation((CPanel.desktop.getWidth() - registroCliente.getWidth()) / 2,
                        (CPanel.desktop.getHeight() - registroCliente.getHeight()) / 2);
            } else {
                registroCliente.dispose();
            }        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnAnotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnotarActionPerformed
        if (!txtNota.getText().isEmpty() || !txtCantidad.getText().isEmpty()
                || !txtObservacion.getText().isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) jtTablaCreditos.getModel();
            String abonoInicial = "";
            try {
                if (txtAbonoInicial.getText().trim().isEmpty()) {
                    abonoInicial = "0";
                } else {
                    abonoInicial = txtAbonoInicial.getText().trim();
                }
                model.addRow(new String[]{txtNota.getText(),
                    FechaHerramienta.formatoYMD(jdcFechaCredito.getDate()),
                    cmbSucursal.getSelectedItem().toString(),
                    cmbClienteCredito.getSelectedItem().toString(), txtObservacion.getText(),
                    cmbMetodoDePago.getSelectedItem().toString(),
                    abonoInicial,
                    txtCantidad.getText()});
                limpiarCreditos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Error", 0);
            }
        } else {
            if (txtNota.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Falto de llenar la Nota");
            }
            if (txtObservacion.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Falto de llenar la Observación");
            }
            if (txtCantidad.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Falto de llenar la Cantidad");
            }
        }
    }//GEN-LAST:event_btnAnotarActionPerformed

    private void limpiarCreditos() {
        txtNota.setText("");
        jdcFechaCredito.setDate(new Date());
        cmbClienteCredito.setSelectedIndex(0);
        txtObservacion.setText("");
        txtCantidad.setText("");
        txtAbonoInicial.setText("");
    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            this.setClosed(true);
            System.gc();
        } catch (PropertyVetoException ex) {
            this.dispose();
            System.gc();
        }          // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentasActionPerformed
        AccesoBD controlBD = new AccesoBD();
        Venta venta = new Venta();
        String fecha = "";
        venta.setNota(jtTablaCreditos.getValueAt(
                0, 0).toString());
        fecha = jtTablaCreditos.getValueAt(0, 1).toString();
        venta.setFechaVenta(FechaHerramienta.convertirStringEnDate(fecha));
        venta.setNombreTienda(jtTablaCreditos.getValueAt(
                0, 2).toString());
        String[] nombreCliente = jtTablaCreditos.getValueAt(0, 3).toString().split("-");
        venta.setNombreCliente(nombreCliente[0]);
        venta.setDescripcion(jtTablaCreditos.getValueAt(
                0, 4).toString());
        venta.setMetodoPago(jtTablaCreditos.getValueAt(
                0, 5).toString());
        double abonoInicial = Double.parseDouble(jtTablaCreditos.getValueAt(0, 6).toString());
        venta.setAbono(abonoInicial);
        double Importe = Double.parseDouble(jtTablaCreditos.getValueAt(0, 7).toString());
        venta.setImporte(Importe);
        double saldoRestante = Importe - abonoInicial;
        venta.setSaldoRestante(saldoRestante);
        if (saldoRestante > 0) {
            venta.setEstatus("Vigente");
        } else {
            venta.setEstatus("Saldado");
        }
        if (controlBD.add(venta)) {
            limpiarCreditos();
            JOptionPane.showMessageDialog(this, "Ventas registradas correctamente", "Datos registrados", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Las ventas no se registraron", "Problemas al guardar", 0);
        }

    }//GEN-LAST:event_btnRegistrarVentasActionPerformed

    private void btnAnotar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnotar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnotar1ActionPerformed

    private void btnGuardarCreditos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCreditos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCreditos1ActionPerformed

    private void btnBorrarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCreditoActionPerformed
        if (jtTablaCreditos.getSelectedRow() > -1) {
            DefaultTableModel model = (DefaultTableModel) jtTablaCreditos.getModel();
            model.removeRow(jtTablaCreditos.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una venta de la "
                    + "tabla para poder borrarla.", "Venta no seleccionada", 0);
        }
    }//GEN-LAST:event_btnBorrarCreditoActionPerformed

    private void jpAbonosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpAbonosComponentShown
        llenarCombos();
        String fechaInicioAbono = FechaHerramienta.formatoYMD(jdcFechaInicio.getDate());
        String fechaFinAbono = FechaHerramienta.formatoYMD(jdcFechaFin.getDate());
        String HQL = "From Venta v WHERE v.nombreCliente = '"
                + cmbClienteAbono.getSelectedItem().toString() + "'"
                + " AND v.fechaVenta BETWEEN '" + fechaInicioAbono + "' and '" + fechaFinAbono + "'";
        cmbClienteAbono.setSelectedIndex(0);
        cargaTabla(jtTablaAbonos, HQL, "Venta");
        jdcFechaCredito.setDate(new Date());
        jdcFechaAbono.setDate(new Date());
        jdcFechaInicio.setDate(new Date());
        jdcFechaFin.setDate(new Date());
        jdcFechaGasto.setDate(new Date());

    }//GEN-LAST:event_jpAbonosComponentShown

    private void jpGastosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpGastosComponentShown
        llenarCombos();
        cargaTabla(jtTablaGastos, "From Compra", "Compra");
        jdcFechaCredito.setDate(new Date());
        jdcFechaAbono.setDate(new Date());
        jdcFechaInicio.setDate(new Date());
        jdcFechaFin.setDate(new Date());
        jdcFechaGasto.setDate(new Date());

    }//GEN-LAST:event_jpGastosComponentShown

    private void jpCreditosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpCreditosComponentShown
        llenarCombos();
        jdcFechaCredito.setDate(new Date());
        jdcFechaAbono.setDate(new Date());
        jdcFechaInicio.setDate(new Date());
        jdcFechaFin.setDate(new Date());
        jdcFechaGasto.setDate(new Date());
        // TODO add your handling code here:
    }//GEN-LAST:event_jpCreditosComponentShown

    private void btnSalirAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAbonosActionPerformed
        try {
            this.setClosed(true);
            System.gc();
        } catch (PropertyVetoException ex) {
            this.dispose();
            System.gc();
        }             // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirAbonosActionPerformed

    private void btnSalirGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirGastosActionPerformed
        try {
            this.setClosed(true);
            System.gc();
        } catch (PropertyVetoException ex) {
            this.dispose();
            System.gc();
        }             // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirGastosActionPerformed

    private void cmbClienteAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteAbonoActionPerformed

    }//GEN-LAST:event_cmbClienteAbonoActionPerformed
    public final void addActions() {
        final ItemListener changeClick = new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (cmbClienteAbono.getItemCount() > 0) {
                    if (cmbClienteAbono.getSelectedItem().equals(e.getItem())) {
                        String fechaInicioAbono = FechaHerramienta.formatoYMD(jdcFechaInicio.getDate());
                        String fechaFinAbono = FechaHerramienta.formatoYMD(jdcFechaFin.getDate());
                        String HQL = "From Venta v WHERE v.nombreCliente = '"
                                + cmbClienteAbono.getSelectedItem().toString() + "'"
                                + " AND v.fechaVenta BETWEEN '" + fechaInicioAbono + "' and '" + fechaFinAbono + "'";
                    }
                }
            }
        };

        this.cmbClienteAbono.addItemListener(changeClick);
    }
    private void chkTodosLosClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkTodosLosClientesMouseClicked
        if (chkTodosLosClientes.isSelected()) {
            cmbClienteAbono.setEnabled(false);
            cargaTabla(jtTablaAbonos, "From Venta", "Venta");
        } else {
            cmbClienteAbono.setEnabled(true);
            String fechaInicioAbono = FechaHerramienta.formatoYMD(jdcFechaInicio.getDate());
            String fechaFinAbono = FechaHerramienta.formatoYMD(jdcFechaFin.getDate());
            String HQL = "From Venta v WHERE v.nombreCliente = '"
                    + cmbClienteAbono.getSelectedItem().toString() + "'"
                    + " AND v.fechaVenta BETWEEN '" + fechaInicioAbono + "' and '" + fechaFinAbono + "'";
            cargaTabla(jtTablaAbonos, HQL, "Venta");
        }


    }//GEN-LAST:event_chkTodosLosClientesMouseClicked

    private void cmbClienteAbonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClienteAbonoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteAbonoItemStateChanged
    private void cargaTabla(final JTable jtTabla, String HQL, String Encabezado) {
        //Reviso si que la consulta no vaya vacia
        if (!HQL.isEmpty()) {
            AccesoBD acceso = new AccesoBD();
            jtTabla.setVisible(false);
            jtTabla.removeAll();
            jtTabla.setModel(acceso.retornaModelo(Encabezado, HQL));
            jtTabla.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonar;
    private javax.swing.JButton btnAnotar;
    private javax.swing.JButton btnAnotar1;
    private javax.swing.JButton btnBorrarCredito;
    private javax.swing.JButton btnGuardarCreditos1;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarVentas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalirAbonos;
    private javax.swing.JButton btnSalirGastos;
    private javax.swing.JButton btnSalirResumen;
    private javax.swing.JCheckBox chkTodosLosClientes;
    private javax.swing.JComboBox cmbClienteAbono;
    private javax.swing.JComboBox cmbClienteCredito;
    private javax.swing.JComboBox cmbMetodoDePago;
    private javax.swing.JComboBox cmbSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jdcFechaAbono;
    private com.toedter.calendar.JDateChooser jdcFechaCredito;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaGasto;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JPanel jpAbonos;
    private javax.swing.JPanel jpCreditos;
    private javax.swing.JPanel jpGastos;
    private javax.swing.JPanel jpResumen;
    private javax.swing.JTable jtTablaAbonos;
    private javax.swing.JTable jtTablaCreditos;
    private javax.swing.JTable jtTablaGastos;
    private javax.swing.JTabbedPane jtpDiario;
    private javax.swing.JTextField txtAbonoInicial;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadAbono;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
